### ISSUE TITLE
Login / register section

### ISSUE THREAD

**Issue by Orhan92** [Orhan92/orhan-albayati-web-project#15]
There a a few bugs that should get fixed. This login / register section does not have to be perfect or in any way encrypted. But we do want it to work properly for its purpose in this project just to show the functionality @gustavnyberg 

- [x] Save the registered user into accounts array PERMANENTLY (now it dissappears as soon as the page reloads/refreshes), I found out some good information for this section. That is that javascript has no idea what is stored once you refresh the page. If you want to fix this issue you should work for example with a database where you push the new member into the database. This can be done, and inside the database I could be checking for duplicate usernames, which also clears another bug that I have. I know how to solve this problem but for this project, I will leave it like this.
- [x] Check for duplicate username during registration. If exists, do not push the new registered object to the accounts array.
- [x] Once the user is logged in, we need to find a way to print the username.

**Comment by gustavnyberg** [comment]
@Orhan92 No problem. I will set this as Done in my end.
