### ISSUE TITLE
Formatting API

### ISSUE THREAD

**Issue by Orhan92** [Orhan92/orhan-albayati-web-project#17]
Fix the formatting of the API on your webapplication. In other words, fix the formatting so that what is shown to the user is user friendly and looks good.

**Comment by Orhan92** [comment]
@gustavnyberg Hey, the reason I'm assigning you is that I can't figure how to select the content that I want to show from the API call.

**Comment by Orhan92** [comment]
Problem solved!

**Comment by gustavnyberg** [comment]
Sweet! 😎

Congrats! 🎉🎊🎈
