### ISSUE TITLE
Responsitivity

### ISSUE THREAD

**Issue by Orhan92** [Orhan92/orhan-albayati-web-project#20]
Clean up the website by checking the responsitivity for all the elements.

**Comment by Orhan92** [comment]
@gustavnyberg My media queries is not responding (The old queries works, but when I try to apply new ones the page doesn't respond to it)

**Comment by Orhan92** [comment]
@gustavnyberg Never mind... I found the solution.. I just forgot to link my queries.css file in the head section.. oops!

**Comment by gustavnyberg** [comment]
👍

We have no further open and ongoing issues, right?
